#--------------------------------------------
# On-Premise OTEL Collector setup
services:
  otel-collector-onprem:
    image: otel/opentelemetry-collector-contrib:0.122.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./etc/otel-collector-onprem.yaml:/etc/otel-collector.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "45679:55679" # zpages extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP http receiver
    depends_on:
      - tempo
      - prometheus
      - loki
    networks:
      - onprem #to simulate network with on-premise environment
      - otelToOtel #to simulate network with otel-collector-oncloud

#--------------------------------------------
# Cloud OTEL Collector setup
  otel-collector-oncloud:
    image: otel/opentelemetry-collector-contrib:0.122.0
    command: [ "--config=/etc/otel-collector.yaml" ]
    volumes:
      - ./etc/otel-collector-oncloud.yaml:/etc/otel-collector.yaml
    ports:
      - "2888:1888"   # pprof extension
      - "9888:8888"   # Prometheus metrics exposed by the collector
      - "9889:8889"   # Prometheus exporter metrics
      - "23133:13133" # health_check extension
      - "5317:4317"   # OTLP gRPC receiver
      - "5319:4319"   # OTLP gRPC receiver
      - "5320:4320"   # OTLP gRPC receiver
      - "55679:55679" # zpages extension
    depends_on:
      - tempo
      - prometheus
      - loki
    networks:
      - cloud #to simulate network with cloud environment
      - otelToOtel #to simulate network with otel-collector-onprem

#--------------------------------------------
# Following are visualization containers
  tempo:
    image: grafana/tempo:2.7.1
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/tempo.yaml:/etc/tempo.yaml
      - ./data/tempo-data:/var/tempo
    ports:
      - "3200:3200"
      - "4321:4321"
    networks:
      - cloud

  loki:
    image: grafana/loki:3.4.2
    command: -config.file=/etc/loki/loki.yaml
    ports:
      - "3100:3100" # loki needs to be exposed so it receives logs
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces # send traces to Tempo
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    volumes:
      - ./etc/loki.yaml:/etc/loki/loki.yaml
      - ./data/loki-data:/tmp/loki
    networks:
      - cloud

  prometheus:
    image: prom/prometheus:v3.2.1
    volumes:
      - ./etc/prometheus.yaml:/etc/prometheus.yaml
      - ./data/prometheus-data:/prometheus/data
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    ports:
      - "9090:9090"
    networks:
      - cloud

  grafana:
    image: grafana/grafana:11.6.2
    volumes:
      - ./data/grafana-data/datasources:/etc/grafana/provisioning/datasources
      - ./data/grafana-data/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./data/grafana-data/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - tempo
      - loki
    networks:
      - cloud

networks:
  onprem:
    driver: bridge
  cloud:
    driver: bridge
  otelToOtel:
    driver: bridge
