receivers:
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4317"

processors:
  memory_limiter:
    check_interval: 1s   # Time between measurements of memory usage
    limit_mib: 1000      # Maximum amount of memory, in MiB
    spike_limit_mib: 500 # Maximum spike expected between the measurements of memory usage
  # batch metrics before sending to reduce API usage
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s         # Time it will wait before sending the data regardless of size

exporters:
  prometheusremotewrite:
    endpoint: "http://prometheus:9090/api/v1/write"
    tls:
      insecure: true
  otlp/tempo:
    endpoint: "tempo:4321"
    tls:
      insecure: true
  otlphttp:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheusremotewrite]
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp]
