receivers:
  # Assuming Prometheus/KSM has been setup
  otlp:
    protocols:
      http:
        endpoint: "0.0.0.0:4318"
#Sample of OTEL Collector Solace for demonstration purpose. Remove if no solace setup
  solace:
    broker: [solace-ip-address:5672]
    max_unacknowledged: 500
    auth:
      sasl_plain:
        username: username
        password: password
    queue: queue://#telemetry-trace
    tls:
      insecure: true
      insecure_skip_verify: true

processors:
  memory_limiter:
    check_interval: 1s # Time between measurements of memorry usage
    limit_mib: 1000 # Maximum amount of memory, in MiB
    spike_limit_mib: 500 # Maximum spike expected between the measurements of memory usage
    
  # batch metrics before sending to reduce API usage
  batch:
    send_batch_max_size: 1000
    send_batch_size: 100
    timeout: 10s # Time it will wait before sending the data regardless of size

exporters:
  otlphttp/metrics:
    endpoint: "http://otel-collector-oncloud:4317"
  otlphttp/logs:
    endpoint: "http://otel-collector-oncloud:4317"
  otlphttp/traces:
    endpoint: "http://otel-collector-oncloud:4317"
  debug:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors:
      exporters: [otlphttp/metrics]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/logs]
    traces:
      receivers: [solace,otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/traces]

